/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PublicVerify_emailRouteImport } from './routes/_public/verify_email'
import { Route as PublicSign_upRouteImport } from './routes/_public/sign_up'
import { Route as PublicSign_inRouteImport } from './routes/_public/sign_in'
import { Route as PublicRecoveryRouteImport } from './routes/_public/recovery'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerify_emailRoute = PublicVerify_emailRouteImport.update({
  id: '/verify_email',
  path: '/verify_email',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSign_upRoute = PublicSign_upRouteImport.update({
  id: '/sign_up',
  path: '/sign_up',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSign_inRoute = PublicSign_inRouteImport.update({
  id: '/sign_in',
  path: '/sign_in',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRecoveryRoute = PublicRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthedSettingsRoute
  '/recovery': typeof PublicRecoveryRoute
  '/sign_in': typeof PublicSign_inRoute
  '/sign_up': typeof PublicSign_upRoute
  '/verify_email': typeof PublicVerify_emailRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AuthedSettingsRoute
  '/recovery': typeof PublicRecoveryRoute
  '/sign_in': typeof PublicSign_inRoute
  '/sign_up': typeof PublicSign_upRoute
  '/verify_email': typeof PublicVerify_emailRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_public/recovery': typeof PublicRecoveryRoute
  '/_public/sign_in': typeof PublicSign_inRoute
  '/_public/sign_up': typeof PublicSign_upRoute
  '/_public/verify_email': typeof PublicVerify_emailRoute
  '/api/health': typeof ApiHealthRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/recovery'
    | '/sign_in'
    | '/sign_up'
    | '/verify_email'
    | '/api/health'
    | '/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/recovery'
    | '/sign_in'
    | '/sign_up'
    | '/verify_email'
    | '/api/health'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/settings'
    | '/_public/recovery'
    | '/_public/sign_in'
    | '/_public/sign_up'
    | '/_public/verify_email'
    | '/api/health'
    | '/_authed/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify_email': {
      id: '/_public/verify_email'
      path: '/verify_email'
      fullPath: '/verify_email'
      preLoaderRoute: typeof PublicVerify_emailRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign_up': {
      id: '/_public/sign_up'
      path: '/sign_up'
      fullPath: '/sign_up'
      preLoaderRoute: typeof PublicSign_upRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign_in': {
      id: '/_public/sign_in'
      path: '/sign_in'
      fullPath: '/sign_in'
      preLoaderRoute: typeof PublicSign_inRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/recovery': {
      id: '/_public/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof PublicRecoveryRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicRecoveryRoute: typeof PublicRecoveryRoute
  PublicSign_inRoute: typeof PublicSign_inRoute
  PublicSign_upRoute: typeof PublicSign_upRoute
  PublicVerify_emailRoute: typeof PublicVerify_emailRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicRecoveryRoute: PublicRecoveryRoute,
  PublicSign_inRoute: PublicSign_inRoute,
  PublicSign_upRoute: PublicSign_upRoute,
  PublicVerify_emailRoute: PublicVerify_emailRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
