/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PublicVerify_emailRouteImport } from './routes/_public/verify_email'
import { Route as PublicSign_upRouteImport } from './routes/_public/sign_up'
import { Route as PublicSign_inRouteImport } from './routes/_public/sign_in'
import { Route as PublicRecoveryRouteImport } from './routes/_public/recovery'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedQuotationsIndexRouteImport } from './routes/_authed/quotations/index'
import { Route as AuthedPayrollIndexRouteImport } from './routes/_authed/payroll/index'
import { Route as AuthedEmployeesIndexRouteImport } from './routes/_authed/employees/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedAttendanceIndexRouteImport } from './routes/_authed/attendance/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedQuotationsNewRouteImport } from './routes/_authed/quotations/new'
import { Route as AuthedQuotationsQuotationIdRouteImport } from './routes/_authed/quotations/$quotationId'
import { Route as AuthedPayrollHistoryRouteImport } from './routes/_authed/payroll/history'
import { Route as AuthedEmployeesNewRouteImport } from './routes/_authed/employees/new'
import { Route as AuthedEmployeesEmployeeIdRouteImport } from './routes/_authed/employees/$employeeId'
import { Route as AuthedClientsNewRouteImport } from './routes/_authed/clients/new'
import { Route as AuthedClientsClientIdRouteImport } from './routes/_authed/clients/$clientId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerify_emailRoute = PublicVerify_emailRouteImport.update({
  id: '/verify_email',
  path: '/verify_email',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSign_upRoute = PublicSign_upRouteImport.update({
  id: '/sign_up',
  path: '/sign_up',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSign_inRoute = PublicSign_inRouteImport.update({
  id: '/sign_in',
  path: '/sign_in',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRecoveryRoute = PublicRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedQuotationsIndexRoute = AuthedQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPayrollIndexRoute = AuthedPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEmployeesIndexRoute = AuthedEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAttendanceIndexRoute = AuthedAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedQuotationsNewRoute = AuthedQuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedQuotationsQuotationIdRoute =
  AuthedQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedPayrollHistoryRoute = AuthedPayrollHistoryRouteImport.update({
  id: '/payroll/history',
  path: '/payroll/history',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEmployeesNewRoute = AuthedEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEmployeesEmployeeIdRoute =
  AuthedEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedClientsNewRoute = AuthedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedClientsClientIdRoute = AuthedClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthedSettingsRoute
  '/recovery': typeof PublicRecoveryRoute
  '/sign_in': typeof PublicSign_inRoute
  '/sign_up': typeof PublicSign_upRoute
  '/verify_email': typeof PublicVerify_emailRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/clients/$clientId': typeof AuthedClientsClientIdRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/employees/$employeeId': typeof AuthedEmployeesEmployeeIdRoute
  '/employees/new': typeof AuthedEmployeesNewRoute
  '/payroll/history': typeof AuthedPayrollHistoryRoute
  '/quotations/$quotationId': typeof AuthedQuotationsQuotationIdRoute
  '/quotations/new': typeof AuthedQuotationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/attendance': typeof AuthedAttendanceIndexRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/employees': typeof AuthedEmployeesIndexRoute
  '/payroll': typeof AuthedPayrollIndexRoute
  '/quotations': typeof AuthedQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AuthedSettingsRoute
  '/recovery': typeof PublicRecoveryRoute
  '/sign_in': typeof PublicSign_inRoute
  '/sign_up': typeof PublicSign_upRoute
  '/verify_email': typeof PublicVerify_emailRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/clients/$clientId': typeof AuthedClientsClientIdRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/employees/$employeeId': typeof AuthedEmployeesEmployeeIdRoute
  '/employees/new': typeof AuthedEmployeesNewRoute
  '/payroll/history': typeof AuthedPayrollHistoryRoute
  '/quotations/$quotationId': typeof AuthedQuotationsQuotationIdRoute
  '/quotations/new': typeof AuthedQuotationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/attendance': typeof AuthedAttendanceIndexRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/employees': typeof AuthedEmployeesIndexRoute
  '/payroll': typeof AuthedPayrollIndexRoute
  '/quotations': typeof AuthedQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_public/recovery': typeof PublicRecoveryRoute
  '/_public/sign_in': typeof PublicSign_inRoute
  '/_public/sign_up': typeof PublicSign_upRoute
  '/_public/verify_email': typeof PublicVerify_emailRoute
  '/api/health': typeof ApiHealthRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/clients/$clientId': typeof AuthedClientsClientIdRoute
  '/_authed/clients/new': typeof AuthedClientsNewRoute
  '/_authed/employees/$employeeId': typeof AuthedEmployeesEmployeeIdRoute
  '/_authed/employees/new': typeof AuthedEmployeesNewRoute
  '/_authed/payroll/history': typeof AuthedPayrollHistoryRoute
  '/_authed/quotations/$quotationId': typeof AuthedQuotationsQuotationIdRoute
  '/_authed/quotations/new': typeof AuthedQuotationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/attendance/': typeof AuthedAttendanceIndexRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
  '/_authed/employees/': typeof AuthedEmployeesIndexRoute
  '/_authed/payroll/': typeof AuthedPayrollIndexRoute
  '/_authed/quotations/': typeof AuthedQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/recovery'
    | '/sign_in'
    | '/sign_up'
    | '/verify_email'
    | '/api/health'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/payroll/history'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/api/auth/$'
    | '/attendance'
    | '/clients'
    | '/employees'
    | '/payroll'
    | '/quotations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/recovery'
    | '/sign_in'
    | '/sign_up'
    | '/verify_email'
    | '/api/health'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/payroll/history'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/api/auth/$'
    | '/attendance'
    | '/clients'
    | '/employees'
    | '/payroll'
    | '/quotations'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/settings'
    | '/_public/recovery'
    | '/_public/sign_in'
    | '/_public/sign_up'
    | '/_public/verify_email'
    | '/api/health'
    | '/_authed/'
    | '/_authed/clients/$clientId'
    | '/_authed/clients/new'
    | '/_authed/employees/$employeeId'
    | '/_authed/employees/new'
    | '/_authed/payroll/history'
    | '/_authed/quotations/$quotationId'
    | '/_authed/quotations/new'
    | '/api/auth/$'
    | '/_authed/attendance/'
    | '/_authed/clients/'
    | '/_authed/employees/'
    | '/_authed/payroll/'
    | '/_authed/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify_email': {
      id: '/_public/verify_email'
      path: '/verify_email'
      fullPath: '/verify_email'
      preLoaderRoute: typeof PublicVerify_emailRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign_up': {
      id: '/_public/sign_up'
      path: '/sign_up'
      fullPath: '/sign_up'
      preLoaderRoute: typeof PublicSign_upRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign_in': {
      id: '/_public/sign_in'
      path: '/sign_in'
      fullPath: '/sign_in'
      preLoaderRoute: typeof PublicSign_inRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/recovery': {
      id: '/_public/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof PublicRecoveryRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/quotations/': {
      id: '/_authed/quotations/'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthedQuotationsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payroll/': {
      id: '/_authed/payroll/'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthedPayrollIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/employees/': {
      id: '/_authed/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthedEmployeesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/attendance/': {
      id: '/_authed/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthedAttendanceIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/quotations/new': {
      id: '/_authed/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AuthedQuotationsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/quotations/$quotationId': {
      id: '/_authed/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof AuthedQuotationsQuotationIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payroll/history': {
      id: '/_authed/payroll/history'
      path: '/payroll/history'
      fullPath: '/payroll/history'
      preLoaderRoute: typeof AuthedPayrollHistoryRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/employees/new': {
      id: '/_authed/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthedEmployeesNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/employees/$employeeId': {
      id: '/_authed/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AuthedEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/clients/new': {
      id: '/_authed/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthedClientsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/clients/$clientId': {
      id: '/_authed/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthedClientsClientIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedClientsClientIdRoute: typeof AuthedClientsClientIdRoute
  AuthedClientsNewRoute: typeof AuthedClientsNewRoute
  AuthedEmployeesEmployeeIdRoute: typeof AuthedEmployeesEmployeeIdRoute
  AuthedEmployeesNewRoute: typeof AuthedEmployeesNewRoute
  AuthedPayrollHistoryRoute: typeof AuthedPayrollHistoryRoute
  AuthedQuotationsQuotationIdRoute: typeof AuthedQuotationsQuotationIdRoute
  AuthedQuotationsNewRoute: typeof AuthedQuotationsNewRoute
  AuthedAttendanceIndexRoute: typeof AuthedAttendanceIndexRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
  AuthedEmployeesIndexRoute: typeof AuthedEmployeesIndexRoute
  AuthedPayrollIndexRoute: typeof AuthedPayrollIndexRoute
  AuthedQuotationsIndexRoute: typeof AuthedQuotationsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedClientsClientIdRoute: AuthedClientsClientIdRoute,
  AuthedClientsNewRoute: AuthedClientsNewRoute,
  AuthedEmployeesEmployeeIdRoute: AuthedEmployeesEmployeeIdRoute,
  AuthedEmployeesNewRoute: AuthedEmployeesNewRoute,
  AuthedPayrollHistoryRoute: AuthedPayrollHistoryRoute,
  AuthedQuotationsQuotationIdRoute: AuthedQuotationsQuotationIdRoute,
  AuthedQuotationsNewRoute: AuthedQuotationsNewRoute,
  AuthedAttendanceIndexRoute: AuthedAttendanceIndexRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
  AuthedEmployeesIndexRoute: AuthedEmployeesIndexRoute,
  AuthedPayrollIndexRoute: AuthedPayrollIndexRoute,
  AuthedQuotationsIndexRoute: AuthedQuotationsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicRecoveryRoute: typeof PublicRecoveryRoute
  PublicSign_inRoute: typeof PublicSign_inRoute
  PublicSign_upRoute: typeof PublicSign_upRoute
  PublicVerify_emailRoute: typeof PublicVerify_emailRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicRecoveryRoute: PublicRecoveryRoute,
  PublicSign_inRoute: PublicSign_inRoute,
  PublicSign_upRoute: PublicSign_upRoute,
  PublicVerify_emailRoute: PublicVerify_emailRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
